import pyfirmata
import time

board = pyfirmata.Arduino('COM4')
it = pyfirmata.util.Iterator(board)
it.start()

led1 = board.get_pin('d:11:o')
led2 = board.get_pin('d:2:o')
led3 = board.get_pin('d:3:o')
led4 = board.get_pin('d:4:o')
led5 = board.get_pin('d:5:o')
led6 = board.get_pin('d:6:o')
led7 = board.get_pin('d:7:o')
led8 = board.get_pin('d:8:o')
led9 = board.get_pin('d:9:o')
led10 = board.get_pin('d:10:o')

while True:
    led1.write(1)
    time.sleep(0.70)
    print("Led 1 = HIGH")
    led2.write(1)
    time.sleep(0.70)
    print("Led 2 = HIGH")
    led3.write(1)
    time.sleep(0.70)
    print("Led 3 = HIGH")
    led4.write(1)
    time.sleep(0.70)
    print("Led 4 = HIGH")
    led5.write(1)
    time.sleep(0.70)
    print("Led 5 = HIGH")
    led6.write(1)
    time.sleep(0.70)
    print("Led 6 = HIGH")
    led7.write(1)
    time.sleep(0.70)
    print("Led 7 = HIGH")
    led8.write(1)
    time.sleep(0.70)
    print("Led 8 = HIGH")
    led9.write(1)
    time.sleep(0.70)
    print("Led 9 = HIGH")
    led10.write(1)
    time.sleep(0.70)
    print("Led 10 = HIGH")
    led1.write(0)
    led2.write(0)
    led3.write(0)
    led4.write(0)
    led5.write(0)
    led6.write(0)
    led7.write(0)
    led8.write(0)
    led9.write(0)
    led10.write(0)
    time.sleep(0.70)
    print("Todos los leds = LOW")

    led10.write(1)
    time.sleep(0.70)
    print("Led 10 = HIGH")
    led9.write(1)
    time.sleep(0.70)
    print("Led 9 = HIGH")
    led8.write(1)
    time.sleep(0.70)
    print("Led 8 = HIGH")
    led7.write(1)
    time.sleep(0.70)
    print("Led 7 = HIGH")
    led6.write(1)
    time.sleep(0.70)
    print("Led 6 = HIGH")
    led5.write(1)
    time.sleep(0.70)
    print("Led 5 = HIGH")
    led4.write(1)
    time.sleep(0.70)
    print("Led 4 = HIGH")
    led3.write(1)
    time.sleep(0.70) 
    print("Led 3 = HIGH")
    led2.write(1)
    time.sleep(0.70)
    print("Led 2 = HIGH")
    led1.write(1)
    time.sleep(0.70)
    print("Led 1 = HIGH")
    led1.write(0)
    led2.write(0)
    led3.write(0)
    led4.write(0)
    led5.write(0)
    led6.write(0)
    led7.write(0)
    led8.write(0)
    led9.write(0)
    led10.write(0)
    time.sleep(0.70)
    print("Todos los leds = LOW")